### ISSUE TITLE
Script from mavrick

### ISSUE THREAD

**Issue by ZwinkaDink** [VindictiveA3/vdic#10]
added MTT from mavrick script

**Comment by ZwinkaDink** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/EAtpACD0/1-test)

**Comment by aguy96** [comment]
[WeaponShops.zip](https://github.com/VindictiveA3/vdic/files/1810357/WeaponShops.zip)
[TalentTreeModular.zip](https://github.com/VindictiveA3/vdic/files/1810359/TalentTreeModular.zip)
[Maverick-ObfuSQF-DesktopClient.zip](https://github.com/VindictiveA3/vdic/files/1810360/Maverick-ObfuSQF-DesktopClient.zip)
[@obfusqf.zip](https://github.com/VindictiveA3/vdic/files/1810361/obfusqf.zip)
