### ISSUE TITLE
LAWYER SHOP

### ISSUE THREAD

**Issue by ZwinkaDink** [VindictiveA3/vdic#100]
this enableSimulation false; this allowDamage false; this addAction[localize "STR_lawyer_clothing",life_fnc_clothingMenu,"lawyer",0,false,false,"",' license_civ_lawyer && playerSide isEqualTo civilian']; this addAction[format ["%1 ($%2)",localize (getText(missionConfigFile >> "Licenses" >> "lawyer" >> "displayName")), [(getNumber(missionConfigFile >> "Licenses" >> "lawyer" >> "price"))] call life_fnc_numberText],life_fnc_buyLicense,"lawyer",0,false,false,"",' !license_civ_lawyer && playerSide isEqualTo civilian ']; this addAction[localize"STR_NOTF_ATM",life_fnc_atmMenu,"",0,false,false,"",' isNull objectParent player && player distance _target < 4 '];

need this added to a shop guy for lawyer

**Comment by ryannadell** [comment]
done
