### ISSUE TITLE
Ryan's Highdea

### ISSUE THREAD

**Issue by ryannadell** [VindictiveA3/vdic#101]
James asked me if we could make cops able to pick up AAF clothing for a fix so he doesn't have to redo the swat uniform for AAF, at the moment BLUFOR cannot pickup or interact with non blufor clothing, but could we make in the police uniform script where AAF clothing could be picked up by them, if we cant do that I came to a highdea (High Idea), we make another windows key addaction that reloads the units texture, making it to where officers dont have to drop clothing anymore to fix the "Uniform check retard" issue. This would mean we dont have to add aaf clothing to a pick up item for blufor and can simply have them buy it at shop and it forces it on them and if they lose texture just hit the windows key and the option for reloading texture and badaboom badabing medium to hard work around.

**Comment by RyanWolfe556** [comment]
Yeah, uhh it's done.
