### ISSUE TITLE
Server Branding 

### ISSUE THREAD

**Issue by ZwinkaDink** [VindictiveA3/vdic#11]
Server Branding on startup and in description

**Comment by ZwinkaDink** [comment]
fixed dispaly message in WelcomeNotification.sqf

**Comment by ZwinkaDink** [comment]
#17

**Comment by ZwinkaDink** [comment]
first Pull request to branding -Pull Request #17

**Comment by RyanWolfe556** [comment]
that is fairly lit

**Comment by ZwinkaDink** [comment]
need server LOGO for splash screen

**Comment by ZwinkaDink** [comment]
5 hours to go still missing textures We need a Texture Guy

**Comment by ZwinkaDink** [comment]
added a temp texture for now to see if it works
