### ISSUE TITLE
Server Advert on NPC clothing

### ISSUE THREAD

**Issue by ZwinkaDink** [VindictiveA3/vdic#13]
add a textured clothing to NPCs (Shops)

**Comment by RyanWolfe556** [comment]
"Across the mans tits"

**Comment by aguy96** [comment]
*No shirt, bare nipples w/ logo*

**Comment by ZwinkaDink** [comment]
fixed dispaly message in WelcomeNotification.sqf

**Comment by ZwinkaDink** [comment]
need texture for the NPC unless we are doing news stands

**Comment by ZwinkaDink** [comment]
was decided to custom make uniforms for each shop
