### ISSUE TITLE
Start Money and Paychecks

### ISSUE THREAD

**Issue by ZwinkaDink** [VindictiveA3/vdic#15]
Start money is 2.5 million
civ checks = 2000
Cop checks = 2500
Medic Checks = 2250
Cop checks increase $500 per Rank

**Comment by RyanWolfe556** [comment]
fixed your mistake

**Comment by ZwinkaDink** [comment]
https://www.altisliferpg.com/topic/759-tutorial-custom-paychecks/

**Comment by ZwinkaDink** [comment]
added in commit #18 setting to intesting
