### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by aguy96** [VindictiveA3/vdic#45]
![107410_20180316032630_1](https://user-images.githubusercontent.com/29053868/37508710-a89c43b8-28ca-11e8-9911-3fd5a27e89ea.png)
![107410_20180316031910_1](https://user-images.githubusercontent.com/29053868/37508711-a8ae61d8-28ca-11e8-9b3a-4dfa62e27842.png)
![107410_20180316032255_1](https://user-images.githubusercontent.com/29053868/37508712-a8bb5f28-28ca-11e8-972c-5541a1e36883.png)
![107410_20180316032611_1](https://user-images.githubusercontent.com/29053868/37508713-a8c97e82-28ca-11e8-9184-6a9f627a6be5.png)
![107410_20180316032627_1](https://user-images.githubusercontent.com/29053868/37508714-a8d94fa6-28ca-11e8-8a9b-f1e219687021.png)

Possibly related to reduced screen resolution?

**Comment by ryannadell** [comment]
User instructed to lower interface size due to monitor size.(Awaiting user response) Possible new UI in future for test, currently researching.

**Comment by RyanWolfe556** [comment]
req. close by reporter
