### ISSUE TITLE
Maverick Scripts V2

### ISSUE THREAD

**Issue by aguy96** [VindictiveA3/vdic#47]
[Navigation.zip](https://github.com/VindictiveA3/vdic/files/1818518/Navigation.zip)
[Tuning.zip](https://github.com/VindictiveA3/vdic/files/1818519/Tuning.zip)

**Comment by ZwinkaDink** [comment]
navigation has been added will need to tag map edits to add tuning. map edits are needed to place the NPC to do the tunning
