### ISSUE TITLE
ATM at truck dealer

### ISSUE THREAD

**Issue by ryannadell** [VindictiveA3/vdic#49]
Atm needed at truck dealer.

-I'm going to add a scroll function the the dealer like I did for gunstore. Possibly could be put in before test release.

-I, NaDell can do this but if one of you gets to it before me let me know!

**Comment by ryannadell** [comment]
Should be on test with current mission SQM, truck dealer was given func for scroll wheel.

**Comment by RyanWolfe556** [comment]
app. Approved.
