### ISSUE TITLE
Flashbang

### ISSUE THREAD

**Issue by ryannadell** [VindictiveA3/vdic#53]
Flashbangs needs to be limited in distance and time it blinds, made to be more realistic.

The M84 Stun grenade upon detonation, it emits an intensely loud "bang" of 170–180 decibels and a blinding flash of more than one million candela within five feet of initiation. It is currently in game set to being five fucking miles.

**Comment by ZwinkaDink** [comment]
dropped range from 25 meters to 10 meters will adjust to get a happy medium also reduced time of pure White screen from 13 sec to 7

**Comment by RyanWolfe556** [comment]
Approved.
