### ISSUE TITLE
Update on Channel 7 News shops

### ISSUE THREAD

**Issue by RyanWolfe556** [VindictiveA3/vdic#65]
-Add EOD vests. V_Press_F "Press Vest" /and  V_EOD_blue_F
-Basic Ballistic Helmet. H_PASGT_basic_blue_press_F "Press Helmet"
-Only wearable by persons with the Press License

**Comment by ZwinkaDink** [comment]
@ryannadell  i need this added to a guy near news station

init="this enableSimulation false; this allowDamage false; 	this addAction[localize ""STR_News_clothing"",life_fnc_clothingMenu,""news"",0,false,false,"""",' license_civ_news && playerSide isEqualTo civilian'];

 need that added to a vendor for news shop
also add 

this addAction[format [""%1 ($%2)"",localize (getText(missionConfigFile >> ""Licenses"" >> ""news"" >> ""displayName"")), [(getNumber(missionConfigFile >> ""Licenses"" >> ""news"" >> ""price""))] call life_fnc_numberText],life_fnc_buyLicense,""news"",0,false,false,"""",' !license_civ_news && playerSide isEqualTo civilian ']; this addAction[localize""STR_NOTF_ATM"",life_fnc_atmMenu,"""",0,false,false,"""",' isNull objectParent player && player distance _target < 4 '];";

to the guy for the licenses and an atm

**Comment by ZwinkaDink** [comment]
this enableSimulation false; this allowDamage false; this addAction[localize "STR_News_clothing",life_fnc_clothingMenu,"news",0,false,false,"", license_civ_news && playerSide isEqualTo civilian];

this addAction[format ["%1 ($%2)",localize (getText(missionConfigFile >> "Licenses" >> "news" >> "displayName")), [(getNumber(missionConfigFile >> "Licenses" >> "news" >> "price"))] call life_fnc_numberText],life_fnc_buyLicense,""news"",0,false,false,"""",' !license_civ_news && playerSide isEqualTo civilian ']; this addAction[localize""STR_NOTF_ATM"",life_fnc_atmMenu,"""",0,false,false,"""",' isNull objectParent player && player distance _target < 4 '];";

**Comment by ZwinkaDink** [comment]
this enableSimulation false; this allowDamage false; this addAction[localize "STR_News_clothing",life_fnc_clothingMenu,"news",0,false,false,"", license_civ_news && playerSide isEqualTo civilian];

this addAction[format ["%1 ($%2)",localize (getText(missionConfigFile >> "Licenses" >> "news" >> "displayName")), [(getNumber(missionConfigFile >> "Licenses" >> "news" >> "price"))] call lif

**Comment by ZwinkaDink** [comment]
this enableSimulation false; this allowDamage false; this addAction[localize "STR_News_clothing",life_fnc_clothingMenu,"news",0,false,false,"", license_civ_news && playerSide isEqualTo civilian];

this addAction[format ["%1 ($%2)",localize (getText(missionConfigFile >> "Licenses" >> "news" >> "displayName")), [(getNumber(missionConfigFile >> "Licenses" >> "news" >> "price"))] call life_fnc_numberText],life_fnc_buyLicense,"news",0,false,false,"",' !license_civ_news && playerSide isEqualTo civilian ']; this addAction[localize"STR_NOTF_ATM",life_fnc_atmMenu,"",0,false,false,"",' isNull objectParent player && player distance _target < 4 '];

**Comment by ZwinkaDink** [comment]
this addAction[localize "STR_News_clothing",life_fnc_clothingMenu,"news",0,false,false,"",' license_civ_news && playerSide isEqualTo civilian'];

**Comment by ZwinkaDink** [comment]
all added and working
