### ISSUE TITLE
Gate: RIGHT THERE. 

### ISSUE THREAD

**Issue by RyanWolfe556** [VindictiveA3/vdic#87]
https://imgur.com/a/BcE6h

oof plz fix make a gate there cause current system is gay.

**Comment by ryannadell** [comment]
042150 -grid ref for my own notes, expect gate done with a small dick made of soda cans by no later than eh idk like 5pm EST monday

**Comment by ryannadell** [comment]
Gate added got a bunch ol' gay dick hidden tho
