### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by ZwinkaDink** [VindictiveA3/vdic#93]
Why are people being left in position that abuse there power and is a cancer to the community. these are the type of people that drive devs and players away i thought this was  going to be a fair place to be for people to hang out and have fun. this is a serious issue that needs more attention than what has be invested into it. i have many players and staff coming to me a DEV and saying how they are unhappy with the decision that was made. i have over 200 dollars worth of work and time spent on this mission file to make it enjoyable . keeping people in staff that does not work well with other staff and the community is a bad decisions.

**Comment by RyanWolfe556** [comment]
Yeah, people I've talked to are upset..

**Comment by aguy96** [comment]
Then tell the people who are fucking upset to come talk to me. I fucking suspend him, I ask for anyone with evidence, comments, concerns to come to me and guess what, fucking nobody does.

**Comment by aguy96** [comment]
So at this point I've told.him.the mingyness and immaturity stops here, and he gets no more warnings.

**Comment by ZwinkaDink** [comment]
i think people are seeing him still with the tag not saying that from my end, but i put this here so the the 2 owners and the devs could talk about it being that it involves the 4 of us. and people dont like going to upper management any where you go its a fear thing and that is why it is filter coming to you we take the general public of the community and condense it so its not just a repeat from many different people.

**Comment by ZwinkaDink** [comment]
and from what i was told people have submitted video and accounts iv had my issues with said person but have talked to him to settle it out
